version: "2.2"

services:
    flask:
        build:
            context: .
            dockerfile: ./Dockerfile
        image: scetts/tts-server:v2
        cpus: 1
        restart: unless-stopped
        environment:
            - "TTS_MODEL_FILE=glowtts-v2/checkpoint_26000.pth.tar"
            - "TTS_MODEL_CONFIG=glowtts-v2/config.json"
            # - "VOCODER_MODEL_FILE=hifigan-v2/best_model_291688.pth.tar"
            # - "VOCODER_MODEL_CONFIG=hifigan-v2/config.json"
            - "VOCODER_MODEL_ONNX=hifigan-v2/hifigan.onnx"
        volumes:
            - "./data/src/flask:/content/src/flask"
            - "./data/models:/content/models"
        ports: 
            - "5000:5000"